# Generated by Django 5.0.8 on 2024-08-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('release_date', models.DateField()),
                ('overview', models.TextField()),
                ('video', models.URLField()),
                ('backdrop_path', models.CharField()),
            ],
        ),
    ]
