# Generated by Django 5.0.8 on 2024-08-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('genre', models.CharField()),
                ('description', models.CharField()),
                ('img', models.ImageField(upload_to='favorites/')),
            ],
        ),
    ]
