# Generated by Django 5.0.8 on 2024-08-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='genre',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='title',
            field=models.CharField(blank=True, null=True),
        ),
    ]
