# Generated by Django 5.0.8 on 2024-08-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_app', '0003_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='favorites/images/'),
        ),
    ]
