# Generated by Django 5.0.8 on 2024-08-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_app', '0004_alter_favorite_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='img',
        ),
        migrations.AddField(
            model_name='favorite',
            name='backdrop_path',
            field=models.CharField(blank=True, null=True),
        ),
    ]
