# Generated by Django 5.0.8 on 2024-08-20 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_app', '0005_remove_favorite_img_favorite_backdrop_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('backdrop_path', models.CharField(blank=True, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
